--- #YAML:1.0
name:               RTPG
version:            0.9
abstract:           is a module for accessing to rtorrent's SCGI functions.
author:
    - Dmitry E. Oboukhov <unera@debian.org>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Carp:              0
    Encode:            0
    MIME::Types:       0
    RPC::XML:          0
    RPC::XML::Client:  0
    RPC::XML::Parser:  0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.55_02
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
